version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - pip install flask

  post_build:
    commands:
      - echo Build completed on `date`
      - python main.py &

artifacts:
  files:
    - main.py
