version: 0.0

os: linux

files:
  - source: /
    destination: /

hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/install_flask.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
    
